version: "3"

services:
  api:
    build: api/.
    volumes:
      - ./api/:/web10 
    ports:
      - "6000:80"
    environment:
      VIRTUAL_HOST: api.localhost
    networks:
      default:
        aliases:
          - api.localhost
  auth:
    build: auth/client
    command: ["npm", "start"]
    volumes:
      - ./auth/client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: auth.localhost
    ports:
      - '3000:3000'
  social:
    build: social/.
    volumes:
      - ./social/:/social    
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: social.localhost
  crm:
    build: crm/.
    volumes:
      - ./crm/:/crm    
    ports:
      - "7746:8000"
    environment:
      VIRTUAL_HOST: crm.localhost
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d/:/etc/nginx/vhost.d

volumes:
  node-modules: