version: "3"

services:
  api:
    build: api
    volumes:
      - ./api/:/web10 
    ports:
      - "6000:80"
    environment:
      VIRTUAL_HOST: api.localhost
    networks:
      default:
        aliases:
          - api.localhost
  auth:
    build: auth
    volumes:
      - ./auth:/frontend
      - node-modules:/frontend/node_modules
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: auth.localhost
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '3000:80'
  crm:
    build: 
      context: .
      dockerfile: crm/Dockerfile
    volumes:
      - ./crm/:/crm
      - ./auth/public/sdk/ :/crm/sdk    
    ports:
      - "7746:80"
    environment:
      VIRTUAL_HOST: crm.localhost
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d/:/etc/nginx/vhost.d

volumes:
  node-modules: