apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: web10
build:
  artifacts:
    - image: gcr.io/pure-phalanx-344719/api
      context: ../../api
    - image: gcr.io/pure-phalanx-344719/auth
      context: ../../auth
    - image: gcr.io/pure-phalanx-344719/crm
      context: ../../crm
      sync:
        infer:
        - 'crm/.'
        - 'auth/public/sdk/.'
deploy:
  kubectl:
    manifests:
      - kuberapi.yml
      - kuberauth.yml
      - kubercrm.yml