apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: web10
build:
  artifacts:
    - image: gcr.io/pure-phalanx-344719/api
      context: ../../api
deploy:
  kubectl:
    manifests:
      - kuberweb10.yml
