apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: web10
build:
  artifacts:
    - image: gcr.io/pure-phalanx-344719/api
      context: ../../api
    - image: gcr.io/pure-phalanx-344719/auth
      context: ../../auth
    - image: gcr.io/pure-phalanx-344719/crm
      context: ../../crm
    - image: gcr.io/pure-phalanx-344719/wapi
      context: ../../wapi
    - image: gcr.io/pure-phalanx-344719/social
      context: ../../social
deploy:
  kubectl:
    manifests:
      - kuberapi.yml
      - kuberauth.yml
      - kubercrm.yml
      - kuberwapi.yml
      - kubersocial.yml
      